version: '3.3'

services:
#ZOOKEEPER
  zookeeper:
      container_name: zookeeper
      restart: always
      image: docker.io/bitnami/zookeeper:3.8
      ports:
        - "2181:2181"
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zookeeper:2888:3888
      networks:
        - flight_network

#KAFKA
  kafka:
      build:
          context: .
          dockerfile: Dockerfile.kafka
      container_name: kafka
      ports:
          - "9092:9092"
      environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
          - zookeeper
      networks:
          - flight_network

#SPARK
spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - flight_network

#ELK
elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - flight_network

#KIBANA
kibana:
    build:
      context: .
      dockerfile: Dockerfile.kibana
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - flight_network

networks:
  flight_network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local

  
        
